apiVersion: v1
kind: Service
metadata:
  name: ht-jaeger
spec:
  selector:
    app: ht-jaeger
  ports:
    - port: 6831
      targetPort: 6831
      protocol: UDP
    - port: 6832
      targetPort: 6832
      protocol: UDP
    - port: 5778
    - port: 16686
    - port: 14250
    - port: 14268
    - port: 14269
    - port: 9411