apiVersion: apps/v1
kind: Deployment
metadata:
  name: ht-otel-collector
spec:
  selector:
    matchLabels:
      app: ht-otel-collector
  template:
    metadata:
      labels:
        app: ht-otel-collector
    spec:
      containers:
        - name: otel-collector
          image: otel/opentelemetry-collector-contrib:latest
          ports:
            - containerPort: 1888
            - containerPort: 8888
            - containerPort: 8889
            - containerPort: 13133
            - containerPort: 4317
            - containerPort: 4318
            - containerPort: 55679
          volumeMounts:
            - name: config-volume
              mountPath: /etc/otelcol-contrib
              readOnly: true
          readinessProbe:
            httpGet:
              path: /
              port: 13133
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: config-volume
          hostPath:
            path: ./otel-collector-config.yaml
            type: File