apiVersion: v1
kind: Service
metadata:
  name: ht-tomcat
spec:
  selector:
    app: ht-tomcat
  ports:
    - port: 8085
      targetPort: 8080
    - port: 9010
      targetPort: 9010
    - port: 1099
      targetPort: 1099