apiVersion: v1
kind: Secret
metadata:
  name: dockerhub-secret
  namespace: hello-telemetry
data:  
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogImVtRm9ZMlZ1T21SamEzSmZjR0YwWDBSU2JVMWtUMnhYTW14SVgwRnNOVGd3V25aV2JFOTJWQzA1VVE9PSIKCQl9Cgl9Cn0=
type: kubernetes.io/dockerconfigjsondata

