apiVersion: v1
kind: Service
metadata:
  name: ht-tomcat
  namespace: hello-telemetry
spec:
  selector:
    app: ht-tomcat
  ports:
    - port: 8080
      targetPort: 8080
    - port: 9010
      targetPort: 9010
    - port: 1099
      targetPort: 1099