apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: ht-vs
  namespace: hello-telemetry
spec:
  gateways:
  - istio-system/digital-factory-tls-gateway
  hosts:
  - ht.zitaconseil.fr
  http:
  - match:
    - uri:
        prefix: /metrics-api/
    name: apmserver
    rewrite:
      uri: /intake/v2/rum/events
    route:
    - destination:
        host: apm-server-apm-http.elastic-system.svc.cluster.local
        port:
          number: 8200
  - route:
    - destination:
        host: ht-tomcat-svc.hello-telemetry.svc.cluster.local
        port:
          number: 8080
