apiVersion: apps/v1
kind: Deployment
metadata:
  name: ht-mysql
  namespace: hello-telemetry  
spec:
  selector:
    matchLabels:
      app: ht-mysql
  template:
    metadata:
      labels:
        app: ht-mysql
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: rootpassword
            - name: MYSQL_DATABASE
              value: mydatabase
            - name: MYSQL_USER
              value: myuser
            - name: MYSQL_PASSWORD
              value: mypassword
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
            # - name: initdb
            #   mountPath: /docker-entrypoint-initdb.d
          readinessProbe:
            exec:
              command:
                - mysqladmin
                - ping
                - "-h"
                - "127.0.0.1"
            initialDelaySeconds: 10
            periodSeconds: 5
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-pvc
        # - name: initdb
        #   hostPath:
        #     path: ./initdb
        #     type: Directory