apiVersion: apps/v1
kind: Deployment
metadata:
  name: ht-python-service
  namespace: hello-telemetry
spec:
  selector:
    matchLabels:
      app: ht-python-service
  template:
    metadata:
      labels:
        app: ht-python-service
        ver: "1.0"
        version: "2.0"
      annotations:
        instrumentation.opentelemetry.io/inject-python: "observability/otel-instrumentation"

    spec:
      containers:
        - name: python-service
          imagePullPolicy: Always
          image: zahcen/hello-telemetry-python-service:latest
          ports:
            - containerPort: 5000
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
      imagePullSecrets:
        - name: dockerhub-secret