apiVersion: apps/v1
kind: Deployment
metadata:
  name: ht-python-service
spec:
  selector:
    matchLabels:
      app: ht-python-service
  template:
    metadata:
      labels:
        app: ht-python-service
    spec:
      containers:
        - name: python-service
          image: ht-python-service:latest
          ports:
            - containerPort: 5000
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5