name: Docker Image CI

on:
  push:
    paths-ignore:
      - '.github/workflowspipeline.yaml' 
    branches: [ "main" ]
  pull_request:
    paths-ignore:
      - '.github/workflowspipeline.yaml'
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Git Checkout
      uses: actions/checkout@v4
    
    - name: Multiple Bash commands
      run: |
        echo "First command"
        ls -al
        ls -al python-service/Dockerfile
              
    - name: Build Docker Image
      id: buildAndPushImage
      uses: MaximilianoBz/dockerhub-buildpush@v1.0
      with:
        registry_url: 'docker.io'
        repository_name: 'hello-telemetry-python-service'
        user_name: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
        image_version: 'latest'
        docker_file: 'python-service'
    
    # - name: Setup kubectl
    #   uses: ThomasKliszowski/setup-kubectl@v1
    #   with:
    #      # Base64 encoded kube config
    #      kube-config: ${{ secrets.KUBECONFIG_B64 }}

    # - name: Apply tomcat Kubernetes manifests
    #   run: |
    #      kubectl version
    #      kubectl apply -f python-service/manifest/
    #      #kubectl rollout restart deploy ariba-simulator -n punchout
         
